Repository SouchetJulie/DevLab, pull requests merged in 2022-07, with the labels that each got.

#41 Ajouter les categories
  package-lock.json
  package.json
  src/client/components/lesson/category-badge.component.tsx
  src/client/components/lesson/detail/LessonDetailsHeader.tsx
  src/client/components/lesson/list/LessonItem.tsx
  src/client/hooks/category-list.hook.ts
  src/client/styles/lesson-item.module.scss
  src/pages/api/category/[_id].ts
  src/pages/api/category/index.ts
  src/pages/lesson/upload.tsx
  src/server/handlers/category/get.handler.ts
  src/server/handlers/lesson/create.handler.ts
  src/server/handlers/lesson/get.handler.ts
  src/server/handlers/user/bookmark/add.handler.ts
  src/server/handlers/user/bookmark/delete.handler.ts
  src/server/handlers/user/get.handler.ts
  src/server/services/categories.service.ts
  src/server/services/lessons.service.ts
  src/server/services/users.service.ts
  src/types/category.interface.ts
  src/types/course.enum.ts
  src/types/lesson.interface.ts
  src/types/subject.enum.ts
  src/types/tag.interface.ts
  src/types/user.interface.ts
  src/types/utility-types.ts
  src/utils/create-empty-user.ts
  tsconfig.json
Labels: enhancement, back, front

#42 Paramétrage de profil
  .env
  next.config.js
  package-lock.json
  package.json
  src/client/components/user/Settings.component.tsx
  src/client/components/user/profile-on-submit.hook.ts
  src/client/hooks/auto-login.hook.ts
  src/client/hooks/refresh-user.hook.ts
  src/pages/api/category/index.ts
  src/pages/api/lesson/index.ts
  src/pages/api/user/index.ts
  src/pages/user/index.tsx
  src/server/common/parse-form.utils.ts
  src/server/handlers/lesson/create.handler.ts
  src/server/handlers/user/update.handler.ts
  src/server/middlewares/authentication/session.middleware.ts
  src/server/services/lessons.service.ts
  src/server/services/storage.service.ts
  src/server/services/users.service.ts
  src/types/user.interface.ts
Labels: enhancement, back

#43 Ajouter les matières aux lecons
  src/client/components/lesson/detail/LessonDetailsHeader.tsx
  src/client/components/lesson/list/LessonItem.tsx
  src/client/components/lesson/list/LessonList.tsx
  src/client/components/menu/UserLinks.tsx
  src/client/styles/globals.scss
  src/client/styles/landing_page/Home.module.scss
  src/client/styles/lesson-item.module.scss
  src/client/styles/lesson/lesson-list.module.scss
  src/client/styles/variables.scss
  src/client/utils/get-username.utils.ts
  src/pages/lesson/upload.tsx
  src/server/services/lessons.service.ts
  src/types/subject.enum.ts
Labels: enhancement, back, front

#74 Features/print
  package-lock.json
  package.json
  src/client/components/lesson/detail/LessonDetailsHeader.tsx
  src/pages/user/bookmarks.tsx
Labels: front, feature

#68 Filtrer les leçons
  package-lock.json
  package.json
  src/client/components/category/CategorySelect.component.tsx
  src/client/components/grade/GradeSelect.component.tsx
  src/client/components/lesson/button/LessonBookmark.tsx
  src/client/components/lesson/button/LessonDelete.component.tsx
  src/client/components/lesson/button/LessonEdit.component.tsx
  src/client/components/lesson/detail/LessonDetails.tsx
  src/client/components/lesson/list/LessonList.tsx
  src/client/components/lesson/list/LessonListFilter.component.tsx
  src/client/components/lesson/list/LessonListItem.tsx
  src/client/components/lesson/list/filter-lesson.ts
  src/client/components/lesson/list/lesson-filter-reducer.hook.ts
  src/client/components/lesson/upload/LessonUpload.component.tsx
  src/client/components/lesson/upload/form/LessonUploadForm.component.tsx
  src/client/components/lesson/upload/form/LessonUploadFormGeneral.component.tsx
  src/client/components/lesson/upload/form/LessonUploadFormMeta.component.tsx
  src/client/components/lesson/upload/lesson-upload-reducer.hook.ts
  src/client/components/menu/LessonLinks.tsx
  src/client/components/subject/SubjectSelect.component.tsx
  src/client/components/ui/Datepicker.tsx
  src/client/components/ui/select-option.utils.ts
  src/client/hooks/fetch-lessons.hook.ts
  src/client/hooks/reducer-actions.utils.ts
  src/client/styles/globals.scss
  src/client/styles/lesson-item.module.scss
  src/client/styles/lesson-list.module.scss
  src/client/styles/lesson/lesson-filter.module.scss
  src/client/styles/lesson/lesson-item.module.scss
  src/client/styles/lesson/lesson-list.module.scss
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/lesson/index.tsx
  src/pages/user/bookmarks.tsx
  src/server/common/parse-form.utils.ts
  src/server/handlers/lesson/create.handler.ts
  src/server/services/lessons.service.ts
  src/server/services/users.service.ts
  src/utils/parse-form.utils.ts
Labels: front

#66 Add dashboard
  src/client/components/dashboard/Card.tsx
  src/client/components/dashboard/DashboardComments.tsx
  src/client/components/dashboard/LastPosts.tsx
  src/client/components/lesson/upload/form/LessonUploadFormMeta.component.tsx
  src/client/components/menu/Footer.tsx
  src/client/components/menu/UserLinks.tsx
  src/client/hooks/fetch-user-lesson.hook.ts
  src/client/styles/dashboard/dashboard.module.scss
  src/client/styles/globals.scss
  src/client/styles/lesson/upload.module.scss
  src/client/styles/variables.scss
  src/pages/dashboard/index.tsx
  src/pages/user/settings.tsx
  src/server/handlers/lesson/create.handler.ts
  src/server/handlers/lesson/get.handler.ts
  src/server/handlers/lesson/update.handler.ts
  src/server/handlers/user/bookmark/add.handler.ts
  src/server/handlers/user/bookmark/delete.handler.ts
  src/server/handlers/user/login/auto-login.handler.ts
  src/server/handlers/user/login/login.handler.ts
  src/server/services/lessons.service.ts
Labels: front, feature

#75 Grouper les catégories par matière
  src/client/components/category/CategorySelect.component.tsx
  src/client/components/lesson/list/LessonListFilter.component.tsx
  src/client/components/lesson/upload/form/LessonUploadFormMeta.component.tsx
  src/client/components/ui/select-option.utils.ts
  src/client/styles/lesson/lesson-item.module.scss
  src/types/category.interface.ts
Labels: front

#76 [user] Fix signup error message
  package.json
  src/client/components/auth/SignUpForm.component.tsx
  src/client/styles/auth/Login.Component.module.scss
  src/client/utils/get-axios-error.utils.ts
  src/server/handlers/user/signup/signup.handler.ts
  src/server/middlewares/sanitization/validate.middleware.ts
  src/server/middlewares/sanitization/validation-error.response.ts
Labels: bug, front

#77 Feature/access dashboard from other user
  src/client/components/auth/SignUpForm.component.tsx
  src/client/components/dashboard/Card.tsx
  src/client/components/dashboard/Dashboard.tsx
  src/client/components/dashboard/DashboardComments.tsx
  src/client/components/dashboard/LastPosts.tsx
  src/client/components/home_page/HomePage.tsx
  src/client/components/landing_page/Access.tsx
  src/client/components/landing_page/Accueil.tsx
  src/client/components/landing_page/Actualites.tsx
  src/client/components/landing_page/LandingCard.tsx
  src/client/components/landing_page/LandingPage.tsx
  src/client/components/landing_page/Temoignage.tsx
  src/client/components/lesson/list/LessonListItem.tsx
  src/client/hooks/fetch-lessons.hook.ts
  src/client/services/lesson.service.ts
  src/client/styles/dashboard/dashboard.module.scss
  src/client/styles/lesson/lesson-item.module.scss
  src/pages/dashboard/[userId].tsx
  src/pages/dashboard/index.tsx
Labels: front, feature

#78 Fix/small fixes
  src/client/components/lesson/detail/LessonDetailsHeader.tsx
  src/client/components/lesson/upload/form/LessonUploadFormGeneral.component.tsx
  src/client/utils/get-axios-error.utils.ts
  src/server/common/parse-form.utils.ts
  src/server/handlers/lesson/create.handler.ts
Labels: bug, back, front

#79 Features/profile
  src/client/components/dashboard/Card.tsx
  src/client/components/lesson/detail/LessonDetailsHeader.tsx
  src/client/components/lesson/detail/LessonDetailsPDFViewer.tsx
  src/client/components/user/Profile.component.tsx
  src/client/components/user/ProfileUserForm.component.tsx
  src/client/components/user/Settings.component.tsx
  src/client/services/lesson.service.ts
  src/client/services/user.service.ts
  src/client/styles/dashboard/dashboard.module.scss
  src/client/styles/lesson/lesson-list.module.scss
  src/client/styles/profile/profile.module.scss
  src/client/styles/variables.scss
  src/pages/user/index.tsx
Labels: css, front, feature

#103 Proposer des nouvelles categories
  src/client/components/category/CategoryCreateModal.component.tsx
  src/client/components/category/CategoryNoOptionsMessage.component.tsx
  src/client/components/category/CategorySelect.component.tsx
  src/client/components/category/category.module.scss
  src/client/components/grade/GradeSelect.component.tsx
  src/client/components/subject/SubjectSelect.component.tsx
  src/client/components/user/Profile.component.tsx
  src/client/components/user/ProfileUserForm.component.tsx
  src/client/services/lesson.service.ts
  src/client/styles/dashboard/dashboard.module.scss
  src/client/styles/profile/profile.module.scss
  src/client/utils/get-axios-error.utils.ts
Labels: enhancement, front

#107 [lesson] Display link to author dashboard in lesson details
  src/client/components/lesson/detail/LessonDetailsHeader.tsx
  src/client/components/ui/Avatar.tsx
  src/client/styles/dashboard/dashboard.module.scss
  src/client/styles/lesson/LessonPost.module.scss
  src/client/styles/ui/avatar.module.scss
Labels: bug, front
